/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedTestImport } from './routes/_authenticated/test'
import { Route as AuthenticatedAccountIndexImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAccountTransactionsImport } from './routes/_authenticated/account/transactions'
import { Route as AuthenticatedAccountSettingsImport } from './routes/_authenticated/account/settings'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedTestRoute = AuthenticatedTestImport.update({
  path: '/test',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAccountIndexRoute = AuthenticatedAccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAccountTransactionsRoute =
  AuthenticatedAccountTransactionsImport.update({
    path: '/account/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsImport.update({
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/test': {
      preLoaderRoute: typeof AuthenticatedTestImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/account/settings': {
      preLoaderRoute: typeof AuthenticatedAccountSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/account/transactions': {
      preLoaderRoute: typeof AuthenticatedAccountTransactionsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/account/': {
      preLoaderRoute: typeof AuthenticatedAccountIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedTestRoute,
    AuthenticatedAccountSettingsRoute,
    AuthenticatedAccountTransactionsRoute,
    AuthenticatedAccountIndexRoute,
  ]),
])

/* prettier-ignore-end */
